// ---------------------------
// This file was generated by Nango (v0.61.3)
// You can version this file
// ---------------------------

export interface GmailHeader {
  name: string;
  value: string;
};

export interface GmailBody {
  size: number;
  data: 'string?';
};

export interface GmailPart {
  partId: string;
  mimeType: string;
  filename: 'string?';
  headers: GmailHeader[];
  body: GmailBody;
};

export interface GmailMessage {
  id: string;
  threadId: string;
  labelIds: string[];
  snippet: string;
  historyId: string;
  internalDate: Date;
  payload: {  headers: GmailHeader[];
  body: GmailBody;
  parts: GmailPart[];};
  sizeEstimate: number;
  raw: 'string?';
};

export interface AsanaTask {
  id: string;
  gid: string;
  name: string;
  notes: 'string?';
  completed: boolean;
  completed_at: 'date?';
  created_at: Date;
  modified_at: Date;
  due_on: 'date?';
  due_at: 'date?';
  assignee: {  gid: string;
  name: string;};
  projects: ({  gid: string;
  name: string;})[];
  workspace: {  gid: string;
  name: string;};
  custom_fields: Record<string, any>[];
};

export interface AsanaProject {
  id: string;
  gid: string;
  name: string;
  notes: 'string?';
  created_at: Date;
  modified_at: Date;
  workspace: {  gid: string;
  name: string;};
  team: {  gid: 'string?';
  name: 'string?';};
  archived: boolean;
  color: 'string?';
};

export interface XeroLineItem {
  lineItemID: string;
  description: string;
  quantity: number;
  unitAmount: number;
  taxType: 'string?';
  taxAmount: number;
  lineAmount: number;
  accountCode: 'string?';
};

export interface XeroInvoice {
  id: string;
  invoiceID: string;
  invoiceNumber: string;
  type: string;
  status: string;
  lineAmountTypes: string;
  date: Date;
  dueDate: 'date?';
  total: number;
  totalTax: number;
  amountDue: number;
  amountPaid: number;
  updatedDateUTC: Date;
  currencyCode: string;
  contact: {  contactID: string;
  name: string;};
  lineItems: XeroLineItem[];
};

export interface XeroContact {
  id: string;
  contactID: string;
  contactStatus: string;
  name: string;
  firstName: 'string?';
  lastName: 'string?';
  emailAddress: 'string?';
  addresses: Record<string, any>[];
  phones: Record<string, any>[];
  updatedDateUTC: Date;
  isSupplier: boolean;
  isCustomer: boolean;
};
